name: Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Pint
        run: composer pint

      - name: Run PHPUnit
        run: composer test

      - name: Run Pint Test
        run: vendor/bin/pint --test

#      - name: Run PHPStan
#        run: vendor/bin/phpstan analyse
